### ISSUE TITLE
version mismatch  2.2.0 vs 2.1.0

### ISSUE THREAD

**Issue by hojak** [docToolchain/docToolchain#1049]
Hi,

for tag v2.2.0 the version ist hard coded to '2.1.0'.

https://github.com/docToolchain/docToolchain/blob/8d63f8a25790c0bb2a9806c514471eab40a87f26/dtcw#L20
https://github.com/docToolchain/docToolchain/blob/8d63f8a25790c0bb2a9806c514471eab40a87f26/dtcw.ps1#L6

Is there a specific reason for this mismatch?

Greetings

Holger

**Comment by rdmueller** [comment]
Thanx for bringing this to my attention.
Versioning is not yet perfect for docToolchain. To see if there are any problem with the new release, I decided to bump the dtcw version later to the new version. This basically works for the normal use cases, since dtcw is deployed not along with the distribution but via doctoolchain.github.io .
Event for the container image, the normal use case is that the project dtcw is used and hence the deploy should work.

I agree that we should fix this for future releases. 
And I wonder if it would help if we now retag the current version? What do you think?

**Comment by mh182** [comment]
FYI. There was a similar discussion about dtcw release in #1030.

**Comment by rdmueller** [comment]
I hope I managed to get this right with the 2.2.1 release.
I guess that heals the problem, doesn't it?

**Comment by mh182** [comment]
Closing since this was addressed.
