### ISSUE TITLE
Config.groovy: no error reported if formats config contains wrong format

### ISSUE THREAD

**Issue by PascalWillig** [docToolchain/docToolchain#1169]
**Describe the bug**
InputFiles = [
              [file: 'test1.adoc', formats: ['h**mt**l']],
              [file: 'test2.adoc', formats: ['html']]
             ]
Typo in formats leads to no error output. Instead only test 2 is processed
**To Reproduce**
1. create typo in InputFiles format
2. run generateHtml
3. No error for file

**Expected behavior**
A error is reported if a not recognized file format is used

**Screenshots**

**Configuration**
docToolchain version LATEST
Gradle 6.7.1
Build time: 2020-11-16 17:09:24 UTC
Revision: 2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin: 1.3.72
Groovy: 2.5.12
Ant: Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM: 1.8.0_362 (Red Hat, Inc. 25.362-b08)
OS: Windows 10 10.0 amd64

**Comment by PacoVK** [comment]
Thanks for reporting this issue. 

I would not classify this behaviour as bug rather than as configuration issue because:
* docToolchain supports multiple different input formats. They are coupled to various tasks, eg. `html` has effect for `generateHTML` but not for `convertToEpub` task.
* There would be an error if you have a typo but only **one** input file that targets `html`
Example:
```
InputFiles = [
      [file: 'test1.adoc', formats: ['hmtl']]
]
```
This will soon be extended and improved for dependent tasks config, see #1137

**Comment by PacoVK** [comment]
#1137 was merged. closing this issue
