### ISSUE TITLE
generateSite: Problem with meta data parsing

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#1209]
**Describe the bug**

If jbake meta data is not defined the right way, the `generateSite`-Task throws an exception:

```
FAILURE: Build failed with an exception.
* Where:
Script '/home/dtcuser/docToolchain/scripts/generateSite.gradle' line: 269
* What went wrong:
Execution failed for task ':generateSite'.
> Index 1 out of bounds for length 1
```

**To Reproduce**

use `:jbake-title:test` in one of your `.adoc` files. Hint: there is a space missing.

**Expected behavior**
Let's output a warning and ignore the line

Location of bug: https://github.com/docToolchain/docToolchain/blob/ng/scripts/generateSite.gradle#L269C1-L271C37

**Comment by PacoVK** [comment]
instead of ignoring the line, what about changing the split mechanism to be able to support non-whitespace separated config? 
```
line = (line - ":jbake-").split(": +", 2)
            jbake[line[0]] = line[1]
```

to something like 

```
line = (line - ":jbake-").split(":", 2)
            jbake[line[0]] = line[1].trim()
```

this should work as the first ":" always will mark the end of the property, right? Everything afterwards will be treated as value. The trim will ensure it behaves the same as the currently used regex pattern. 

WDYT?

**Comment by rdmueller** [comment]
You are right. The reason behind my solution was that I thought, without the space is not asciidoc conform and should be fixed...

WDYT?

**Comment by PacoVK** [comment]
Totally agree with your approach. Thanks for clarification 👍 we should encourage to be in line with asciidoc specs
