### ISSUE TITLE
Config for exportChangelog

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#126]
## Expected behavior and actual behavior.

Expected: only the git changelog of the documentation folder is exported

current behaviour: the folder where the docs are stored can change and thus the location of the folder has to be moved to a config file. It is currently hardcoded in the task.

https://github.com/docToolchain/docToolchain/blob/master/scripts/exportChangelog.gradle

**Comment by jakubjab** [comment]
I think this task is an extension rather than core feature of docToolchain. It is tightly coupled to Git and is useless for people using Perforce, Subversion, ClearCase, etc. Moreover, different authors may have different opinion what to show in the log.

I think this should be split into 2 parts:
a) docToolchain can take changelog using an abstract interface, convert it to asciidoc and then PDF, HTML, publish to Confluence, etc.
b) Integrator of docToolchain needs to provide implementation of that interface, giving changelog contents to docToolchain, using whatever source control tools they have.

Then we could provide a few reference implementations as examples, to be reused by integrators, for most common cases.

**Comment by jakubjab** [comment]
However, in the short term, I'll just provide a configuration file for exporting changelog.

**Comment by rdmueller** [comment]
I love your last comment :-) And I agree to the first one. But with the amount of time we have at hand...
