### ISSUE TITLE
Gradle initArc42 creates files in "wrong" folder

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#139]
## Expected behavior and actual behavior.

Expected: I would expect the files to be created (like it was in the "old" version) in .`/src/docs`

Actual: they are created in `./src` cluttering up my normal project code

## Steps to reproduce the problem.

    .\gradlew.bat -b init.gradle initArc42EN

## Specifications like the version of the project, operating system, or hardware.

tried to apply the template to a standard gradle project

**Comment by rdmueller** [comment]
I see, the correct command would have been

    .\gradlew.bat -b init.gradle initArc42EN "-PdocDir=./src/docs"

**Comment by jakubjab** [comment]
With the latest fix, you shouldn't be able to run ".\gradlew.bat -b init.gradle initArc42EN", because the build should fail due to undefined property newDocDir. Is that not failing for you?

**Comment by rdmueller** [comment]
To be honest, I didn't use the latest version. But even with the latest version, I would have used '.' as directory.

How can we make sure that the user knows what he is doing?

**Comment by jakubjab** [comment]
I guess we could check the given path and make sure the certain directories are not affected. So that we would allow either:
a) use src/docs if they want documentation in the same directory tree as the tool
b) use any other directory if they want documentation independently from the tool

Personally I would even forbid option a) - you are not usually putting your Java project inside JDK source directory, you treat JDK as a tool and keep it separate, right?

**Comment by rdmueller** [comment]
> Personally I would even forbid option a) - you are not usually putting your Java project inside JDK source directory, you treat JDK as a tool and keep it separate, right?

asciidoctor and grails have /src/docs as default. I think it does not harm - it will not be included in jars or wars as far as I know....

regarding the defaults. I managed to come up with a script which asks for parameters if they are not specified. This is part of #132 

Shall we close this for now?

**Comment by jakubjab** [comment]
Fine for me.
