### ISSUE TITLE
publishToConfluence goal makes &amp;&amp; out of &&

### ISSUE THREAD

**Issue by dietmar-calmbach-mpf** [docToolchain/docToolchain#153]
I have the following Section in adoc file:

[source,bash,options="nowrap",subs="attributes"]
----
[[ $(hostname) = wpp* ]] && ARTIFACTORY="wpp-tb-git1-de1.i.fhe3rz.net:8081" || ARTIFACTORY="10.70.40.244"

The generated html file displays that correcly.

But when published to confluence it shows:
[ $(hostname) = wpp* ]] &amp;&amp; ARTIFACTORY="wpp-tb-git1-de1.i.fhe3rz.net:8081" || ARTIFACTORY="10.70.40.244"

Is there a way to overcome this?

**Comment by rdmueller** [comment]
I can't find the problem in the source code. I guess confluence itself encodes the double `&&`
have to do some more tests to see what's wrong...

**Comment by dietmar-calmbach-mpf** [comment]
I solved the problem by adding an additional replaceAll to unescapeCDATASections:

def unescapeCDATASections = { html ->
    def start = html.indexOf(CDATA_PLACEHOLDER_START)
    while (start > -1) {
        def end = html.indexOf(CDATA_PLACEHOLDER_END, start)
        if (end > -1) {
            def prefix = html.substring(0, start) + CDATA_PLACEHOLDER_START
            def suffix = html.substring(end)
            def unescaped = html.substring(start + CDATA_PLACEHOLDER_START.length(), end)
                    .replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&amp;', '&')
            html = prefix + unescaped + suffix
        }
        start = html.indexOf(CDATA_PLACEHOLDER_START, start + 1)
    }
    html
}

**Comment by rdmueller** [comment]
That's cool. Would you mind to create a pull request?

**Comment by bodewig** [comment]
I vaguely recall what's going on there, has been some time.

The Confluence API expects certain textual content to be contained inside of a `CDATA` section, even though there shouldn't be any difference between `CDATA` and correctly escaped XML. In my experiments my code samples obviously never contained any ampersands, so the suggested fix looks correct to me.

I wonder whether asciidoc performs replacements for `"` -> `&quot;` and `'` -> `&apos;` as well. If so we need to unescape them as well.

In either case the `&amp` unescape should be the last (as suggested) in order to avoid `&amp;gt;` getting unescaped to `>`.

**Comment by bodewig** [comment]
just had a quick check, it doesn't seem to escape (double) quotes. PR to follow.

**Comment by rdmueller** [comment]
thanx for fixing this!
