### ISSUE TITLE
Updating a page on confluence fails

### ISSUE THREAD

**Issue by mindyou** [docToolchain/docToolchain#161]
The following line 
https://github.com/docToolchain/docToolchain/blob/f4617c314dd78ea09c928dfe4011496938e6123d/scripts/asciidoc2confluence.groovy#L428
seems to have an issue.
Changing the `title~'"` to `title='"` fixes the issue.
with the typo, Confluence is not able to find the page to be updated, tries to create a new page with the same name as the existing page and all of the publishing fails.

**Comment by bodewig** [comment]
I don't think this is a typo, `~` is the "contains" operator in CQL - see https://developer.atlassian.com/server/confluence/cql-operators-reference/

**Comment by rdmueller** [comment]
could it be that it is a problem with the title? Does it start with a number?
There still seems to be something odd with the way confluence finds pages...

I would be great if we could narrow down your problem... 

The page which docToolchain trues to uodate already exists?
Created manually or by docToolchain?
Are there any special characters in the title? like a dash?

**Comment by mindyou** [comment]
Thanks for your quick reaction!
This is the title of the page: "High Level Architecture - R18.3".
It has been a while since I last worked with the Confluence API myself.

**Comment by mindyou** [comment]
I just reverted the change and have worked around it by removing the dash from the title.
Thanks for the suggestion.

**Comment by jakubjab** [comment]
If the doctoolchain indeed doesn't support dashes in the page titles, then I think it should be fixed or at least documented.

**Comment by bodewig** [comment]
+1 to @jakubjab 

We are using CONTAINS because it is case insensitive, not because we really want to perform a substring search, right? In that case maybe we can enclose the title in extra double quotes turning it into a phrase - https://developer.atlassian.com/server/confluence/performing-text-searches-using-cql/ ? I'm not sure phrases are searched in a case insensitive way. Alternatively we can escape special characters - see the bottom of http://lucene.apache.org/core/4_4_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Term_Modifiers . Unfortunately I'd need more time to set up a Confluence test environment in order to to more than just throwing in ideas.

**Comment by rdmueller** [comment]
yes, that's a nasty bug.
I guess the best fix is to first read the whole page structure and then do a local search.
what do you think?

**Comment by jakubjab** [comment]
I wish CQL supported plain old regular expressions instead their own home-made invention. But anyway, let’s take a step back and decide how it should behave. How about:
- we only update pages that were created by us
- we only create pages below given parent page
Then we can think of some solution.

**Comment by bodewig** [comment]
This is a sound policy.

As we need to download the page anyway in order to determine the hash we may want to reject overwriting existing pages that don't contain a hash.  We also need to consider the case where no `ancestorId` has been specified - also checking when we are creating trees of pages may become a bit more difficult (i.e. when there is a preamble or we create sub-pages for `sect2`s).

I was about to reopen this issue but it probably deserves a separate ticket of its own.
