### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Niubi90hou** [docToolchain/docToolchain#169]
## Expected behavior and actual behavior.
<img width="982" alt="bildschirmfoto 2018-07-04 um 21 33 55" src="https://user-images.githubusercontent.com/40838974/42292369-430a8b7c-7fd2-11e8-90f6-3d14f04e4686.png">

## Steps to reproduce the problem.

<img width="583" alt="bildschirmfoto 2018-07-04 um 21 36 54" src="https://user-images.githubusercontent.com/40838974/42292386-637db5dc-7fd2-11e8-97a0-cc578635edbd.png">

## Specifications like the version of the project, operating system, or hardware.

can't create html file. Where is the problem?

**Comment by rdmueller** [comment]
lets see. I guess you've already read the docs (https://doctoolchain.github.io/docToolchain/#_how_to_install_doctoolchain) but something is missing so that you don't succeed. 😐

it seems that you want to use docToolchain as command as descriped. But you have to set the path to your install-dir/bin . that will at least fix your current problem.

what might be easier to vet a start is to first use the gradle approach: you've already checked out the whole project. A `gradlew generateHTML` should build the manual and thus give you a starting point.

hope this helps...

**Comment by Niubi90hou** [comment]
<img width="949" alt="bildschirmfoto 2018-07-04 um 22 35 38" src="https://user-images.githubusercontent.com/40838974/42293457-ab514b50-7fda-11e8-95e7-66320d8a7b2f.png">
<img width="810" alt="bildschirmfoto 2018-07-04 um 22 35 54" src="https://user-images.githubusercontent.com/40838974/42293462-b63299c0-7fda-11e8-8d85-0f6e76e3b14a.png">

**Comment by Niubi90hou** [comment]
<img width="467" alt="bildschirmfoto 2018-07-04 um 22 38 13" src="https://user-images.githubusercontent.com/40838974/42293501-fa5e722c-7fda-11e8-8c04-b4c62ad1d270.png">

**Comment by rdmueller** [comment]
The path for your cloned copy seems to be `/Users/youkesen/`Teste`
so, calling `/Users/youkesen/Teste/bin/doctoolchain <docdir> generateHTML` could already do the trick where <docdir> should be the absolute path to your fodler with the documents.

To make it easier to use, you should add the path of docToolchain to your path environment variable by adding something like this to your `.bashrc` (if you use ubuntu)

    export PATH="$PATH:/Users/youkesen/Teste/bin"

this will allow you to call docToolchain by using the command `doctoolchain`

**Comment by rdmueller** [comment]
I will see what I can do to prepare a full step-by-step example tomorrow

**Comment by Niubi90hou** [comment]
Im using a Mac, it would be grateful if you can help.

**Comment by rdmueller** [comment]
sorry that I couldn't make it yet - a traffic yam destroyed my plans.
did you find a solution?
