### ISSUE TITLE
check and fix configuration of src/docs folder

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#229]
the code seems to run fine if all docs are in `src/docs` folder. Let's move them and see if all tasks adhere to the configuration...

**Comment by ghp-dev** [comment]
I'm  trying to find the mental model of the potential directory structure layouts we might be facing when using doctoolchain from 
1) PATH or from 
2) a submodule.

Is this currently documented somewhere? 
I'm currently testing using doctoolchain in both scenarios for two directories with different layouts:

Folder A
```
.
├── arc42-template.adoc
├── images
│   ├── 05_building_blocks-DE.png
│   ├── 08-Crosscutting-Concepts-Structure-DE.png
│   └── arc42-logo.png
└── src
    ├── 01_introduction_and_goals.adoc
    ├── 02_architecture_constraints.adoc
    ├── 03_system_scope_and_context.adoc
    ├── 04_solution_strategy.adoc
    ├── 05_building_block_view.adoc
    ├── 06_runtime_view.adoc
    ├── 07_deployment_view.adoc
    ├── 08_concepts.adoc
    ├── 09_design_decisions.adoc
    ├── 10_quality_scenarios.adoc
    ├── 11_technical_risks.adoc
    ├── 12_glossary.adoc
    ├── about-arc42.adoc
    └── config.adoc
```

Folder B

```
.
└── src
    └── docs
        ├── arc42-template.adoc
        ├── images
        │   ├── 05_building_blocks-DE.png
        │   ├── 05_building_blocks-EN.png
        │   ├── 08-Crosscutting-Concepts-Structure-DE.png
        │   ├── 08-Crosscutting-Concepts-Structure-EN.png
        │   ├── 10_stimulus.png
        │   └── arc42-logo.png
        └── sub
            ├── 01_introduction_and_goals.adoc
            ├── 02_architecture_constraints.adoc
            ├── 03_system_scope_and_context.adoc
            ├── 04_solution_strategy.adoc
            ├── 05_building_block_view.adoc
            ├── 06_runtime_view.adoc
            ├── 07_deployment_view.adoc
            ├── 08_concepts.adoc
            ├── 09_design_decisions.adoc
            ├── 10_quality_scenarios.adoc
            ├── 11_technical_risks.adoc
            ├── 12_glossary.adoc
            ├── about-arc42.adoc
            └── config.adoc
```

**Comment by rdmueller** [comment]
these ascii-arts are beautiful! we should copy them over to the documentation...!

I always use variant B. It is the default setting of the asciidoctor plugins and is also lets you easily combine your docs, code and tests in one repo. You will then have folders like `docs`, `java` and `tests` underneath the `src` folder.

**Comment by ghp-dev** [comment]
I agree, we should document the relevant folder structures. I will then focus on Folder structure B too.

Kudos to Steve Baker: his [tree  command](http://mama.indstate.edu/users/ice/tree/) produces this output.

**Comment by rdmueller** [comment]
the tree command is cool.

btw: there is also the monotree plugin for asciidoctor

https://github.com/allati/asciidoctor-extension-monotree

**Comment by ghp-dev** [comment]
Good to know, as soon as I have fully set up my docs repo, I will play with that :-)

**Comment by ePex** [comment]
Hey, @ghp-dev in #228 you mentioned the following regarding my change: https://github.com/ePex/docToolchain/commit/65ac3388d615d09fa4cb7dc3f9670150bf44bbd8 (I changed the old commit referenced in #228 since the pdfThemeDir property change broke the generatePDF target and the old one was fine)

"an (empty) src/docs folder has automatically been created" 
This is a little bit weird because this doesn't happen to me. I just created a complete new folder with a src directory and executed the init command like this (with the commit in my repo): 
./gradlew -b init.gradle initArc42DE -PnewDocDir=/absolute/path/to/new/directory/src/docs
and I end up with the following structure: 

```bash
.
└── src
    └── docs
        ├── Config.groovy
        ├── arc42-template.adoc
        ├── images
        │   ├── 05_building_blocks-DE.png
        │   ├── 08-Crosscutting-Concepts-Structure-DE.png
        │   └── arc42-logo.png
        ├── pdfTheme
        │   └── custom-theme.yml
        ├── scripts
        │   ├── ChangelogConfig.groovy
        │   └── ConfluenceConfig.groovy
        └── src
            ├── 01_introduction_and_goals.adoc
            ├── 02_architecture_constraints.adoc
            ├── 03_system_scope_and_context.adoc
            ├── 04_solution_strategy.adoc
            ├── 05_building_block_view.adoc
            ├── 06_runtime_view.adoc
            ├── 07_deployment_view.adoc
            ├── 08_concepts.adoc
            ├── 09_design_decisions.adoc
            ├── 10_quality_scenarios.adoc
            ├── 11_technical_risks.adoc
            ├── 12_glossary.adoc
            ├── about-arc42.adoc
            └── config.adoc
```

**Comment by ghp-dev** [comment]
Hey, @ePex thanks for mentioning this.
After looking into this again,  I noticed that I might have taken a wrong turn somewhere down the track:
I've used docToolchain-v1.0.0 and I've updated a Config.groovy file different from yours. :-(

So this time I tried to follow your repro steps as closely as possible:
```
git clone --recursive https://github.com/docToolchain/docToolchain.git
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git
cd docToolchain

initialize from scratch and build with

./gradlew -b init.gradle initArc42EN -PnewDocDir=/absolute/path/to/my/project/src/docs
```

the above steps worked without a problem.

But then the weirdness started again with the next line 
```
doctoolchain /absolute/path/to/my/project/src/docs generateHTML
```

I don't have doctoolchain on my path.
This means I would call `./bin/doctoolchain`.
but in `bin/` there is no executable file, but a directory:

```
ghp@machine:/datadisk/temp/docToolchain$ ll bin/
insgesamt 12
drwxrwxr-x  3 ghp ghp 4096 Nov 14 19:23 ./
drwxrwxr-x 12 ghp ghp 4096 Nov 14 19:23 ../
drwxrwxr-x  2 ghp ghp 4096 Nov 14 19:23 docToolchain/
ghp@machine:/datadisk/temp/docToolchain$ 
``` 
Now I'm scratching my head...

**Comment by rdmueller** [comment]
hm. regarding your `bin`-folder: don't know why it is empty. The repository contains a `.bat` file for windows and a bash script: https://github.com/docToolchain/docToolchain/tree/master/bin

Regarding the way you install or use docToolchain:

There are several ways...

a) as you described it, you can "install" docToolchain as a shell command. I see 2 drawbacks with this approach: all projects use the same version of docToolchain and when you clone a project, you need to have docToolchain installed to get it running

b) the first approach was to clone the whole repository and merge it with your project repository. I can't recommend this anymore because docToolchain will then be hard to update. The current version of docToolchain is the best example for this approach

c) you could apply only a subset of the needed script plugins directly from github. Again I wouldn't recommend this.

d) add docToolchain as git submodule to your project. This is described here: https://docs-as-co.de/getstarted/tutorial2 . If you already have a repository, you can skip some of the steps mentioned.

In my opinion, d) is the best approach since the submodule is a link to a certain commit of docToolchain and it is stored and versioned along with your project.

htmlSanityCheck is a perfect example for this approach: https://github.com/aim42/htmlSanityCheck

I hope this helps.

**Comment by ePex** [comment]
@ghp-dev regarding the missing doctoolchain binary: I don't have it on my path anyway my comment was just for an example. anyway it is weird that the binary is missing, are you using windows? any directory permission issues maybe? I have the shell script as well as the the bat file. 

@rdmueller I wouldn't go for b) as well because of the same reasons you mentioned above. But I would prefer a) instead of d) because I don't like submodules in git (which is indeed a personal preference). Yes you are right you can't build the docs when you choose to keep doctoolchain outside of the project out of the box but my argument is: of course the docs need to be maintained but you could include a simple readme file inside of your project on how to setup doctoolchain as a tool. I mean the whole project / setup would not fail if you don't have doctoolchain but in my opinion it is a more clean setup to keep the tool separated from the project code and just leave the doc and the config for itself within the project. Yes you use the same version for all project but that is maybe the way you want to go if you think of corporate identity styles for e.g. pdf themeing.

In general: what do you think about my change? I don't think it is the best approach but solves the problem for now but inputPath equals to docPath now in my version.

**Comment by gernotstarke** [comment]
I'd suggest to offer BOTH options (submodule and separate-ways), so users are free to decide about their specific setup.

One approach for @rdmueller's comment above (item a, shell command) would be to execute the docToolchain command with the current directory/folder as parameter.

Is it feasible to have docToolchain distributed via sdkman? It is likely to be accessible on windows any time soon (https://medium.com/@sdkman_/sdkman-is-dead-long-live-sdkman-e6afbe3dc6c3)

**Comment by ePex** [comment]
In the end, I think it is personal preference isn't it? It works fine as submodule and as standalone "cli tool". A distribution channel like sdkman would make the standalone install indeed even easier. 

But aren't we getting off topic a little bit? I thought the "main issue" regarding this discussion is that the generation of HTML isn't working out of the box when you clone the repo, and call init with the default settings.

Am I wrong?

**Comment by gernotstarke** [comment]
you're right - sorry for "hijacking" this issue ..

**Comment by PacoVK** [comment]
This issue is quite old, is there something left to do? Otherwise we should close this.
