### ISSUE TITLE
Readme says "master" or "1.0.0", but "1.1.0" was recently released.

### ISSUE THREAD

**Issue by SoftwareApe** [docToolchain/docToolchain#262]
I'm assuming since the release 1.1.0 is already available, that we shouldn't decide between master and 1.0.0 but rather master and 1.1.0.

**Comment by rdmueller** [comment]
Anne Isabella Thackeray Ritchienx for pointing me at this.
I wasn't aware that the tag will pop up in the relases section.

The 1.0.0 is still the latest and most stable release.

I've setup a docker image to create a new,  more independent deployment option. This image has to reference a repository version. That's why I created the 1.1.0 tag (it includes a new feates, that's why 1.1.x).

If this version works for you - perfect. The main difference is that I don't know if the command line version (the shell scripts in the /bin folder) still work as described. It seems I broke the `includeFolder` setup with my latest changes.

it is now important that we find a versioning schema which supports the stability of this project.

In addition, we need to work on automated tests to have a better indicator to see if something has been broken.

**Comment by SoftwareApe** [comment]
Thanks for the response. I'm currently trying to set it up, mostly having trouble with the proxy config. I did try 1.1.0 but it seems to be gradle issues. 

When I have a working setup I might be able to contribute something on 1.1.0

**Comment by SoftwareApe** [comment]
Thank you. I got the proxy working now, I had the http:// in front of the proxy, and gradle sadly doesn't complain, but didn't take it either.

That document might be a good addition to the getting started of docToolchain (after all my main reason for trying docToolchain is that I'm forced to document in Docupedia, but I want our devs to have the beauty of Docs-As-Code). So I'm guessing most people have proxy problems.

I think I'm hitting the includeFolder issue now :).

    Execution failed for task ':initExisting'.
    > Could not get unknown property 'newDocDir' for object of type org.gradle.api.internal.file.copy.CopySpecWrapper_Decorated.

**Comment by rdmueller** [comment]
yes, setting up the proxy is a pain! Glad you managed it and reported back you experience.
Would you mind to add it to the manual?

I don't use the 'initExisting' task, but there should be an automated test and better docs for it.
As you can see from the source, it simply copies the config over to your own project:
https://github.com/docToolchain/docToolchain/blob/master/init.gradle#L18

**Comment by rdmueller** [comment]
close this, because it is outdated. I think we managed to have a better version management by now. we are at 2.2.0 at the moment
