### ISSUE TITLE
Executing gradlew has warnings because of bad paths

### ISSUE THREAD

**Issue by SoftwareApe** [docToolchain/docToolchain#269]
When executing `gradlew` I get plenty of warnings, such as:
```shell
asciidoctor: WARNING:
image to embed not found or not readable:
<DIRECTORY>/docToolchain/src/docs/images/ea/Manual/htmlSanityCheck.png
```

These images seem to all exist, but they're in `images/Manual`, not `images/ea/Manual`

**Comment by rdmueller** [comment]
`images/ea` is the folder to which `exportEA` writes its files. So maybe I haven't checked so files in.

You are working on the 1.0.0 tag? It seems to me that the Master-HEAD contains all those images...

My goal is to mainly work on the HEAD in order to make another stable release so that we can discard the old 1.0.0 ...

**Comment by SoftwareApe** [comment]
I'm working on 1.0.0 right now, because I want to get the stable release working properly first.

**Comment by rdmueller** [comment]
ok. then let's fix this on the new branch I've created.
I think we only have to copy the images over. I would suggest to copy them from the master branch.

**Comment by PacoVK** [comment]
This issue is quite old, is there still something to do? Otherwise we should close it

**Comment by mh182** [comment]
Closing. If this pops up again, we will reopen it.
