### ISSUE TITLE
Disable Confluence Table of Content

### ISSUE THREAD

**Issue by sabatmonk** [docToolchain/docToolchain#384]
There is no way to disable table of content when publishing to confluence. :!toc: doesn't work. 

A setting in Config.groovy that allow the disabling of the ToC

I've added the code in my local script, but i want to make sure this feature is not existing before making a PR to add it.

If you confirm there is no way to do this, i will create a PR to add this.

**Comment by rdmueller** [comment]
hm. I've never experienced problems with the toc.

In this line, the Confluence TOC is activated for the generated page, but I guess this is not what you mean, is it?
https://github.com/docToolchain/docToolchain/blob/master/scripts/asciidoc2confluence.groovy#L519

I guess I never experienced this problem, because I always use `:toc: left` and in this case, the `publishToConfluence` task will ignore the toc. And I guess you use the standard toc which is rendered as a normal paragraph in front of the document - so the script will pick it up and publish it as a confluence page.

So, if you already have a fix for disabling it, please submit it as PR. It would make sense to mention in the docs when this setting will be necessary...

**Comment by sabatmonk** [comment]
This was done with the PR
