### ISSUE TITLE
Build adoc using images stored in a tree structure

### ISSUE THREAD

**Issue by chess-levin** [docToolchain/docToolchain#407]
Hi guys,

we want to use docToolchain because of its great publish to confluence feature. Now we are struggling with our existing document folder structure. Our project-documentation is stored in a folder tree like this:

```
+ documents
| 
+-- pdfTheme
| 
+-- ci_dubai
    |
    + architecture
        |
        + assets
            |
            + styles
    |
    + cluster
        |
        + assets
    |
    + plugin
        |
        + assets
```

All assets (e.g. images) for the adocs are stored in the assets subfolder.

We are trying to configure our input like this in the config.groovy:

```
inputFiles = [
        [file: 'ci_dubai/architecture/arc1.adoc',  formats: ['html','pdf']],
]

taskInputsDirs = ["ci_dubai/architecture/assets"]
```

The HTML is generated, but  the images referenced from the assets folder are never found by asciidoctor. There is always a warning thrown: 

> asciidoctor: WARNING: image to embed not found or not readable:

The path shown in the WARNING is not correct. E.g. the architecture folder is missing in the path! It looks like the individual document root folder we are using is not working with docToolchain.

The asciidoctor gradle-plugin could be configured to pick up recursively each adoc from each folder  and using the assets stored in the adjacent assets folder.

* How can we configure docToolchain to work with this folder structure?
* Is there a way to tell generateHTML to look into each assets folder for images?
* How could we say translate and publish all adoc you find unser ci_dubai?
* Could ant style globbing patterns used for input =[:] or inputFiles = [:] ?

Any help appreciated.

**Comment by rdmueller** [comment]
thanx for reporting this issue. Let's see how I can help...

I once made the decision that you have to specify each file to be converted. Why? because if you make up your main documents from subdocument which you include, then asciidoctor converts too many files. 

Glob style is currently not implemented but I would be happy to accept a pull request. The code needed to be changed is here: https://github.com/docToolchain/docToolchain/blob/master/scripts/AsciiDocBasics.gradle#L127

The goal is to check if the source files can be found. If some sources are not found, output a warning. If no sources can be found, output a warning and search for all `.adoc` files in the project..

Regardings the images. I guess you don't specify the `imagesdir`, do you? If you don't specify it, it will default to some folder which seems to be different to the one docToolchain uses. (the default is `images` https://github.com/docToolchain/docToolchain/blob/master/scripts/AsciiDocBasics.gradle#L84)

Maybe we should fix this too. But for now, you can specify the `imagesdir` in your file like this:

`:imagesdir: assets`

That should do the trick.

It is good practice to make this definition in a file called `config.adoc` and include it from your files as `include::config.adoc[]`

hope this helps and thanx for using docToolchain!

**Comment by chess-levin** [comment]
Thx for your quick answer. We decided to stick to our old method of generating the html and use docToolchain only for publishing to confluence.

**Comment by rdmueller** [comment]
a very valid decision! I guess I can close this isse for now - please open a neew one if you have any other question or suggestion!
