### ISSUE TITLE
Offline build

### ISSUE THREAD

**Issue by rico-chet** [docToolchain/docToolchain#499]
**Is your feature request related to a problem? Please describe.**
At work, we build firmware for embedded systems, and support period for these is rather lengthy (10 years). Thus, we cannot rely on internet resources during build, otherwise we might not be able to fix a bug and deliver a new version in a deterministic way. 
In other words, we do offline builds.

We cannot get docToolchain to build offline because gradle complains about missing JARs, even though it has its cache (we believe).

We started to use docToolchain for a less important component to give it a try and we aren't happy yet. We use arc42 for this attempt.

**Describe the solution you'd like**
A working example for offline build of a PDF from an arc42 AsciiDoc template.

**Describe alternatives you've considered**
For now, we build the docs on developer machines, but we don't see it as feasible long-term. We consider switching to plain AsciiDoctor, losing much of the versatility that docToolchain provides.

**Additional context**
To make it clear, of course a developer would build on her machine, letting gradle download all dependencies and then storing these files in a tarball, which is checked in and unpacked during CI build for the docToolchain to re-use (with the `--offline` argument for gradle). We tried this but didn't succeed yet. As a firmware team, we don't have much experience with Java, Gradle, Maven etc. so we need some help here.

**Comment by rdmueller** [comment]
interesting and understandable requirement.
In companies who use java as the main development language, a proxy like https://jfrog.com/artifactory/ is often used to fulfill your requirement. Artifactory sits in between the gradle build and the external dependencies. It then caches all fetched dependencies in order to implement a build which is independent of external dependencies.

But as I do understand, such a setup would be too complex for your use case.

Another solution could be to set up a docker image which then caches the dependencies, but I guess docker is also not on your shopping list.

So, to get back to your approach, I think you could succeed by setting the gradle users home directory to be inside of your project. It seems that this directory contains all the cached dependencies whcih you need for an offline build:

https://docs.gradle.org/current/userguide/directory_layout.html

This site explains how to set the gradle user home directory:
https://blog.mrhaki.com/2010/09/gradle-goodness-changing-gradle-user.html

Regarding your alternative: it depends on what features you use. If you just use plain asciidoc, I guess it is a good choice to just use plain Asciidoctor. If you need some more functionality of docToolchain, take a look at the scripts folder - there you'll find all the scripts which implement the functionality. They are mostly independent. This allows you to extract some needed functionality for your own project.

**Comment by rico-chet** [comment]
In fact, my company provides an Artifactory instance and we use it for storing binary stuff used in build (e.g. pre-compiled GNU toolchains), but not for caching, as we don't perceive such a caching repository as a reliable long-term storage (maybe we just lack trust in our IT, but it's a different story).

We even use a docker image during build which we create from scratch on-the-fly from an Artifactory-stored Debian ISO to ensure that we don't depend on Debian mirrors yet are able to add more build dependencies later when needed, without a hassle. It's fun :-)

And yes, we set the gradle user home directory explicitly and store its content to use during offline builds, though it doesn't work yet.

We also use Confluence and MediaWiki (getting obsolete nowadays). We intend to move our content from MediaWiki to AsciiDoc in git and to generate Confluence content during build. This is a reason for us to make docToolchain work as well as possible.

Today, I created a test script which reproduces our scenario quite well: [gist](https://git.io/JkSm3). Interestingly, while writing this test, the gradle daemon gave me headaches (specifically, as I tried to `git add $GRADLE_USER_HOME`, git complained that some files had changed and their names pointed me to the daemon), so turned the daemon off -- and the test passed!

So, it seems that while the daemon is running, it doesn't flush all of its data to the  `$GRADLE_USER_HOME` in a timely manner. At the time a developer saves content of `$GRADLE_USER_HOME` in a tarball, it's not complete. So, building offline with such a tarball fails due to faulty files. So far, this is the hypothesis.

I will try this at work next week and I'll let you know if it works.

**Comment by ewoks** [comment]
Don't want to hijack the issue, but if you have docker experience you could use docker image of docToolchain.
I'm not sure if the latest code is in the latest docker image, but I was working with my own image (slightly modified Dockerfile using the newest source code) and docToolchain worked great to generate PDF from asciidoc, pull data from Jira & finally publish docs to the confluence. 
@rdmueller can give the update on the latest docker image, but if you want ad-hoc test I don't mind providing you link to the image I was experimenting with

**Comment by ewoks** [comment]
@rico-chet I added suggestion [to your gist](https://gist.github.com/rico-chet/497b97ddc7a79385ffbe43ce4470854e#gistcomment-3540865). Basically it is how I used docToolchain with a docker image. I provide externalized configuration via Config.groovy (confluence, jira settings) in a mapped volume folder, spin the container for a given tasks and at the end, after job is done, results (PDF, generated asciidoc, etc) are in the mapped folder.

**Comment by rico-chet** [comment]
@ewoks I understand that containerized workflow has its merits. I [elaborated a bit on this topic in the gist](https://gist.github.com/rico-chet/497b97ddc7a79385ffbe43ce4470854e#gistcomment-3540995), which I'd rather use for discussing containerized build further, when needed.

**Comment by rdmueller** [comment]
this also looks promising, but I haven't tried it yet:
https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:shared-readonly-cache

**Comment by rico-chet** [comment]
That's useful with many ephemeral (_cattle_) containers, which isn't the case for us, we only have one container and our data is extracted _once_. And it's an incubation feature.

Anyway, I tried the `--no-daemon` switch and it seems to work for me in the actual scenario as resembled by the gist posted above. Now, next step is to try it on the build server and see if it works. Will do it next week, as planned.

**Comment by rdmueller** [comment]
another pointer to a good resource: https://twitter.com/j2r2b/status/1468534527811330051

**Comment by rdmueller** [comment]
I think this tutorial solves this issue:
http://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/120_self-contained-dtc.html
