### ISSUE TITLE
Discussion: new releases

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#511]
the process of installing docToolchain was never something I liked so far.
That is why I tried to do some work on it.

The current result is a script called docToolchain-wrapper or short `dtcw` which you can download to a new project simply by issuing

`wget doctoolchain.github.io/dtcw`

with a `chmod +x dtcw`, you have a script at hand which

- tried to find an existing docToolchain installation
- - check if it has been installed through sdkman
- - check if it has been installed manually or via `dtcw`
- - check if docker is available to use the docker image

if docToolchain is not installed as CLI tool and docker is not available, it will be downloaded and installed in the home directory of the user.

I would like to get this new mechanism out as soon as possible, but I wonder how this can be tagged as 'beta' without disturbing other users.

This needs a release on github (upload a zip from the ng-branch), a release on sdkman (no problem) and a release on docker hub (how is this currently triggered?)

cc: @ewoks @jakubjab

**Comment by ehmkah** [comment]
The idea sounds good, but at the moment I think it would have a great value to launch release 1.3.0 in docker hub and sdkman. If those two ways work its really easy for a lot of people (including me) to get doctoolchain up and running.

If the "latest" tag in dockerhub is a little briddle its (for me) not that big deal because there are  tags which defined versions available. So do not be afraid to launch a beta as latest. 

Maybe we should think about the dowloadpart of the wrapper. Because if sdkman is available the wrapper could use sdkman. And if the wrapper downloads everything which is required than next question would be how the wrapper updates.

**Comment by ewoks** [comment]
I agree 100%. I would definitely go for new release and new docker image of it (maybe I would even call it v1.3.0).
New installation feature can be tagged with 1.3.1-alpha (or beta) so it is clear what its state is. Experimental work until this new installation is stable, tested and validated can be continuously improved on its feature branch and when ready released as v1.3.1
Does that make sense?

**Comment by rdmueller** [comment]
ok. so let's first go for the 1.3.0 release

**Comment by rdmueller** [comment]
I think we have results in regards to the releases. 
Do you have any feedback?
