### ISSUE TITLE
Use newer version of Asciidoctor Reveal.js

### ISSUE THREAD

**Issue by sobkowiak** [docToolchain/docToolchain#517]
docToolchain uses actually the older version of the RevealJS generator from Asciidoc. Is it possible to upgrade the code to use the new version?

**Comment by rdmueller** [comment]
as I do understand, we only have to update the reveal.js sources - correct?

**Comment by ehmkah** [comment]
Maybe updating reveal.js and asciidoctor-reveal can both be updated. So the play well together. 

Should we go to the newest version which is 4.1.0?  I hope is possible to set the tag which should be checked out in the ressources folder.

**Comment by ehmkah** [comment]
Updating is not that easy. First PR: https://github.com/docToolchain/docToolchain/pull/527/ (upgrades to reveal 3.9.2 and asciidctor-reveal 2.0.1) - Newer versions become more deifficult because they require newer versions of the asciidoctor which requires newer versions of the ascidoctor gradle pluging which requires some changes to build, I did not understand (at the moment)

With the provided PR we use newest possible versions of reveal reveal-asciidoctor without affecting things outside the `generateDeck`

**Comment by rdmueller** [comment]
hm. what happened to this Issue?
@ehmkah are we already on the latest version which works with the asciidoctor plugin?

**Comment by ehmkah** [comment]
The sad truth is: I was not able to upgrade the used asciidoctor gradle plugin. Its still version 2.4.0 So the issue remains open

**Comment by mh182** [comment]
We should take a look into this after we integrate #1098

**Comment by mh182** [comment]
Was upgraded to Asciidoctor Gradle Plugin 3.3.2
