### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ehmkah** [docToolchain/docToolchain#519]
Four days ago version 1.3.0 has been released. That was really good. 

I had a chat with @rdmueller about the "future of the releasing" (sounds larger than it was). The goal is to have smallest possible gap between "master" "doctoolchain manual on the web" and "release docker-image". In short the idea was to to release a version after a Pullrequest has been merged and the travis build state remains green. Than a new docker image would be built with this version too. Semantic versioning should be use. So for non breaking features the minor version should be raised. 

So after the next PR a version 1.4.0 would come. Than a 1.5.0 and so on. 

- Any opinions? 
- Is it a problem to have so many versions?

**Comment by ewoks** [comment]
I don't see the problem with it, we should just stick to minor bump when there are minor changes (so 1.3.0 -> 1.3.1 -> ... -> 1.3.199 ..) instead of bumping to 1.4.0 without any new feature added. For example, adding new installation method for me would mean new feature, therefore 1.4.0 is logical release, but fixing issues, slight improving existing features and similar, IMO we should bump just the bugfix. We can discuss if breaking changes would mean New major (2.0) or minor bump. How does that sound?

**Comment by rdmueller** [comment]
semantic versioning. 
I agree that we should release a new version with (nearly) each PR.
Let's increase the version like this:

x.y.z
* for minor changes bugfixes, let's increase z
* for additional features (new task) let's increase y
* for breaking changes let's increase x

we also have to keep a changelog. I guess we should follow the advice on https://keepachangelog.com/en/1.0.0/

what is also important is the process for new realeases. We have to document this and automate it as good as we can. A release should include:

- release on gihub with a reduced distribution file (https://github.com/docToolchain/docToolchain/blob/ng/build.gradle#L134)
- release on dockerhub
- release on sdkman

does this match your thoughts?

**Comment by ehmkah** [comment]
I made PR which transform the changelog-file. I moved everything to the release where it belongs. I relied on the date I did not check that it realy come in on that date. I did not fill the gaps for all the changes which have never been logged. 

Hopefully it simplified the future releasing.
