### ISSUE TITLE
exportOpenApi breaks

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#520]
out of the box, I get an error message when I want to build docToolchain:

```
FAILURE: Build failed with an exception.

* Where:
Script '/home/rdmueller/projects/docToolchain/scripts/exportOpenApi.gradle' line: 40

* What went wrong:
A problem occurred evaluating script.
> No such property: value for class: org.gradle.api.internal.provider.DefaultProperty

```

https://github.com/docToolchain/docToolchain/blob/master/scripts/exportOpenApi.gradle#L40

**Comment by rdmueller** [comment]
@ewoks I already had to merge a fix - can you please check that it doesn't break the openAPI task?

**Comment by ewoks** [comment]
Was there OpenApi specification file available in $Docdir, as defined in OpenApi section of your Config.groovy?

**Comment by rdmueller** [comment]
hm. no. just plain doctoolchain without a project

**Comment by ewoks** [comment]
Ok, I will take a look and try to reproduce it

**Comment by rdmueller** [comment]
I just re-checked this. The task shouldn't be executed if not called. So, I think the best solution is to wrap the whole body in a `doLast {}`-block.
Next, it sould fail with a note on what to do. Let me prepare a PR for this.

**Comment by ewoks** [comment]
makes sense.. it is weird that we didn't notice that strange behavior before.. Thanks for PR preparation

**Comment by rdmueller** [comment]
btw, the code is:

```
inputSpec = "${docDir}/${specFile}" // plugin is not able to find file if inputPath is defined as '.'
logger.info("inputSpec: ${inputSpec.value}")
```

So, `inputSpec` is a String - why `.value`?

**Comment by rdmueller** [comment]
I was wrong - wrapping it makes no sence because the code is in the configuration for the task.

only problem seems to be the `.value` on the string. Any idea why it was there?

**Comment by ewoks** [comment]
tbh, don't remember now, but I'm pretty sure it worked when initial PR is made. I will need to check in details

**Comment by mh182** [comment]
I tested `exportOpenAPI` with the [pet-sample](https://dzone.com/articles/a-sample-openapi-30-file-to-get-started) openAPI spec file. The adoc file generated by `exportOpenAPI` was created in `build/OpenAPI/index.adoc` (which means this issue can be closed).

I have some questions how I can integrated the generated file into a documentation.

How would I:
- change the desired output name from `index.adoc` to something like `petstore-v2.0.adoc`?
- how would I include the generated file in my documentation located in `src/docs/my-doc.adoc` from the `build` directory (i.e. not storing the generated file in the git repo)?
- how could I change the location of the generated file so it would reside in `src/docs` so that I can put it under version control?

```
├── build
│   └── OpenAPI
│       └── index.adoc
├── docToolchainConfig.groovy
├── dtcw
└── src
    └── docs
        ├── my-docu.adoc
        └── petstore-v2.0.yaml
```
