### ISSUE TITLE
help needed: where is the CSS defined which is used in documents, created by doctoolchain?

### ISSUE THREAD

**Issue by aisbergde** [docToolchain/docToolchain#558]
**Is your feature request related to a problem? Please describe.**

I like the html files generated by doctoolchain.

That's why I wanted to use the https://github.com/docToolchain/arc42-template-project as template for a microsite for documentation, which uses the doctoolchain technology

But I don't like the CSS styles in the files in this website template, especially the toc. The toc style has `position: fixed`, no scrollbars and can't be used for big toc. I can't find a solution how to solve the issue.

On the other side I would like to just using the style which is generated by doctoolchain by default. But I can find the css only in the created html documents. I can't find, where and how this CSS parts are defined. Maybe this is hard coded in doctoolchain, why not, would be fine.

My idea was, that there could be some CSS files which I just could copy into the website template, and then maybe adapt a bit.

**Describe the solution you'd like**

I would like to find in the documentation where and how the CSS style is defined. And maybe also how to apply this style to pages that (like the website template) are created with doctoolchain.

**Comment by rdmueller** [comment]
thanx for your report.

it turns out that the arc42-template-project was defined as a long lasting project but soon will be replaced with the new docToolchain approach:

```
curl -Lo dtcw doctoolchain.github.io/dtcw
chmod +x dtcw
./dtcw installTemplate
./dtcw generateSite
````

(there is also a powershell dtcw.ps1 script)

as a result, you will have a repository with _only_ the adoc files plus a config and the doctoolchain-wrapper dtcw.

to be honest, I also don't like the default styles.
So, there is a 

    ./dtcw cooyThemes

command which copies all templates to you projects. You will find the styles in /src/site/content/assets (I hope I remembered this correctly). 
Change the files you need to change and delete all other files. docToolchain will overwrite the internal files with your changed ones.

The goal is to then create an external theme from these changes files which can be configured.

dies this help?

**Comment by aisbergde** [comment]
I downloaded dtcw.ps1, changed access
it looks like, the correct downloads are

```
./dtcw downloadTemplate
./dtcw generateSite
```

I used an empty folder and it worked. I got a ready site. Very simple if you know how to do it!

Some remarks:

- It looks like the CSS is the same as used by https://github.com/docToolchain/arc42-template-project
- The site contains some content (for example HomePage content, some content from the About) which is not defined in the src folder. But it is was clear, how.
- Then I followed your instruction `./dtcw copyThemes` , and now I get an idea how this works. Now I get something similar to the https://github.com/docToolchain/arc42-template-project
- when building the site using generateSite, sometimes I get 
  "There is insufficient memory for the Java Runtime Environment to continue."  
  I don't get this error with other Java applications.
- It's one thing to be able to quickly create a site from a template. It's another thing to be able to maintain that site. Furthermore, it's not clear to me yet how simple or complicated that can get. So far I see problems with finding better CSS and also with creating the navigation in an easier way. For example for a wiki pages.

I think, I will investigate, and I will also have a look on Antora. Antora describes a separation of content and UI, and navigation can be controlled with asciidoc lists. This is what I currently miss in the project template. How well do doctoolchain and Antora fit together?

**Comment by rdmueller** [comment]
> Some remarks:
>
> It looks like the CSS is the same as used by https://github.com/docToolchain/arc42-template-project

yes, currently it is the same. But I am already working on using the minimal mistakes theme as standard.

> The site contains some content (for example HomePage content, some content from the About) which is not defined in the src folder. But it was not clear, how.

Yes, I still need some time for the docs.

> Then I followed your instruction ./dtcw copyThemes , and now I get an idea how this works. Now I get something similar to the https://github.com/docToolchain/arc42-template-project

Yes, the inner working is something like this:
- use the internal theme
- copy over this an external theme, if specified
- copy over this the repository theme

This mechanism will let you easily change parts of the theme without creating a whole new theme

> when building the site using generateSite, sometimes I get
> "There is insufficient memory for the Java Runtime Environment to continue."
> I don't get this error with other Java applications.

yes, that's still a bug. Hope it will be resolved soon

> It's one thing to be able to quickly create a site from a template. It's another thing to be able to maintain that site. Furthermore, it's not clear to me yet how simple or complicated that can get. So far I see problems with finding better CSS and also with creating the navigation in an easier way. For example for a wiki pages.

The goal is to focus on the docs. Let someone from your company build a theme (yes, there will be docs for this) and everybody uses it.
Regarding the current CSS - the theme is a standard twitter bootstrap theme. That could help.

> I think, I will investigate, and I will also have a look on Antora. Antora describes a separation of content and UI, and navigation can be controlled with asciidoc lists. This is what I currently miss in the project template. How well do doctoolchain and Antora fit together?

Yes, Antora might be a good alternative. I don't use it because I think there is value in a landing page and blog on the site, which I get with jBake out of the box.
And Antora is "only" a static site generator. You get some more features with docToolchain.
But you can use it both also together. Setup an Antora repository, copy the docToolchain wrapper to it and you can use docToolchain for tasks like exportExcel.

**Comment by aisbergde** [comment]
For my database-documentation-generator I decided to use Antora: https://datahandwerk.github.io/

- Antora default UI can be used nearly "out of the box" and the result is fine
- Antora navigation concept is fine to generate navigation depending on database structure

On the other hand - and compared to docToolchain

- It is more elaborate to understand and set up Antora than docToolchain
- xref are very powerful, but they are a one-way street and only work within Antora
- the sources of the documentation must be in a certain structure
- It is not possible to use any content outside the Antora structure as sources. Or only with great difficulty or effort.
- That's why "code-as-docs" is rather not possible, since code is usually not distributed in folders in an Antora-appropriate form


I wrote a blog post in German: http://datahandwerk.aisberg.de/2021-04-20-docs-code-mit-asciidoc-und-antora/

**Comment by rdmueller** [comment]
thanx for this valuable feedback and your blog post!

**Comment by houserockr** [comment]
This issue _seems_ to be really helpful for me. I'm trying to make minor changes to the CSS embedded into the generated HTML by the `generateHTML` task.

I copied the templates into my project with the `copyThemes` task, which gives me a selection for `pdfTheme` and `jBakeTheme`. I selected `jBakeTheme`, since we already have a working custom pdf theme. This will give me a new subdir `site` containing `assets/css/asciidoctor.css`.

However, if I make any changes to that CSS, they won't be applied during `generateHTML`. My gut tells me it has something to do with the path or an environment variable or config parameter I don't know about. I'm completely in the dark with this.

Does anybody have a hint for me?

**Comment by rdmueller** [comment]
@houserockr the theme within the site folder does only work for `generateSite`, not for `generateHTML`.

For `generateHTML`, the easiest way to change CSS styles is to use a HTML passthrough block within your docs: https://docs.asciidoctor.org/asciidoc/latest/pass/

this will look something like this

```
++++
<style>
div { color: red;}
</style>
++++
```

You can add such a block in a `_config.adoc` file and include it from other files, where you need it.

Asciidoctor also supports additional attributes to change the css style, but they are harder to use from my point of view (https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/#html-styling-attributes)

Hope this helps. I will close this issue now, because I think the original issue is solved. Feel free to continue the discussion here within the closed issue (notifications will be send) or open a new one.

**Comment by houserockr** [comment]
Thank you very much @rdmueller the CSS pass through works like a charm.
This made my day.
