### ISSUE TITLE
docToolchain needs long to build

### ISSUE THREAD

**Issue by ComanderKai77** [docToolchain/docToolchain#587]
**Describe the bug**
The build time to generate the HTML and PDF takes roughly 1 minute.
Is that normal?

**To Reproduce**
1. Create a new project with the arc42DE template
2. Build HTML and PDF

**Expected behavior**
The build should take less than ~10 seconds

**Screenshot**
![image](https://user-images.githubusercontent.com/10358137/118565259-2469cb80-b772-11eb-8282-1355c9397bf4.png)

I've tested it with GitHub Actions so you can see my project
https://github.com/ComanderKai77/docToolchain/runs/2605338100

**Configuration**
 - GitHub Actions on Ubuntu latest
 - Also tested on Debian on a local computer and it takes also longer than 1 minute

**Comment by rdmueller** [comment]
you are right. The generateHTML task should be faster.
The problem is the startup time for gradle. 

You could insert another task - for instance `doctoolchain . tasks` - before `generateHTML` and you'll see that this task will take a long time and generateHTML will run in aprox 9 seconds.

So, the question is, how we can speed up the gradle start up.
I tried to run gradle with `--no-deamon` but it didn't really help.

Now I tried to follow the caching hints explained here: https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle#caching-dependencies

this helped to bring the build time down in the second run:

![image](https://user-images.githubusercontent.com/1856308/118613795-5f462080-b7bf-11eb-83cb-e667dd9fda6d.png)

Hope this helps
