### ISSUE TITLE
generateSite: images-hrefs not correct

### ISSUE THREAD

**Issue by dieterbaier** [docToolchain/docToolchain#831]
When I use the generateSite task within the generated site, the images-hrefs got rendered like `../..//images/someImage.png`. Note the double-slash before 'images'.

When I change the `header.gsp` within the template like adding `content.body = content.body?.replaceAll('//images', '/images')` after the line `content.body = content.body?.replaceAll('src="/', 'src="' + content.rootpath)` the href is rendered correct.

**To Reproduce**
1. see error

**Expected behavior**
The images-href is correct, after the site is rendered

**Screenshots**

**Configuration**
- docToolchain wrapper: V0.29
- use docker installation
- 
 - docToolchain version: V2.0.5
 - OS: MacOS
 - Browser chrome
------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          14-ea (Oracle Corporation 14-ea+33)
OS:           Linux 5.10.76-linuxkit amd64

**Additional context**

**Find a good headline**
Now it is time to find a good headline/subject for the problem.
Please prefix it with the name of the task which fails.

Example:
exportContributors throws exception when ...

**Comment by bit-jkraushaar** [comment]
Source of the problem is https://github.com/docToolchain/docToolchain/blob/8061694f844820f3d477266ff4f5572444ea9962/scripts/generateSite.gradle#L58

`config.microsite.contextPath` is initially set to '/'. This leads to the duplicated double slashes. A workaround is to set `contextPath` to ''. This works at least locally. I have not tested it with a deployed version.

IMHO bugfix would be to add the slash conditionally if contextPath does not end with a slash.
