### ISSUE TITLE
Docs: Feedback for 'Install docToolchain' clone.ps1 file missing

### ISSUE THREAD

**Issue by jneis-at-hilscher** [docToolchain/docToolchain#933]
Trying to set this up on a Win10 machine to evaluate.

When I run the "./dtcw.bat tasks --group=doctoolchain" command I get an error that resources\clone.ps1 could not be found.
The only script in the folder is a clone.sh script.
While it appears to only use commands also supported by powershell changing it to a .ps1 file does not work.
On windows the cd command does not support the "cd -" function to return to the previous directory.

---
#page: https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/020_tutorial/010_Install.adoc
#branch: ng

**Comment by rdmueller** [comment]
thanx for the feedback. 

When I take a look at the sources, I see that the `dtcw.bat` uses the `clone.ps1` file instead of `clone.sh`. It also uses the powershell way of going back to the working directory:

https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw.bat#L137

Could you please try to fetch the latests `dtcw.bat` script?

If this still doesn't work, can you copy and paste the output here?

btw: you should use powershell and thus `dtcw.ps1` instead of `cmd.exe` with `dtcw.bat` - at least if possible.

the powershell version needs some config to allow powershell to run unsigned scripts downloaded from the net. the `.bat` version is a workaround for this problem.

**Comment by jneis-at-hilscher** [comment]
Hi, I tried downloading everything again and it didn't work.

I'm using the .bat as a workaround for the .ps1 script since I can't change the config.

I just checked the repo and there is no clone.ps1 script in the [resources](https://github.com/docToolchain/docToolchain/tree/ng/resources)  folder, only clone.sh

**Comment by rdmueller** [comment]
so, first of all, I added the `clone.ps1` file, but it shouldn't be needed yet. (and it it not part of v2.1.0), you currently have to download it manually.)

But that is not the main problem here. It seems that there is something wrong with `dtcw.ps1`...

argh. wrong comparison. fixed.

you need to download `dtcw.bat` again and then it should work.

thanx for reposting this blocker!

**Comment by jneis-at-hilscher** [comment]
Thanks for solving the problem this quick!
